export default CurrencyData = [
  {currency: 'AED - United Arab Emirates dirham', value: 'AED'},
  {currency: 'AFN - Afghan afghani', value: 'AFN'},
  {currency: 'ALL - Albanian lek', value: 'ALL'},
  {currency: 'AMD - Armenian dram', value: 'AMD'},
  {currency: 'ANG - Netherlands Antillean guilder', value: 'ANG'},
  {currency: 'AOA - Angolan kwanza', value: 'AOA'},
  {currency: 'ARS - Argentine peso', value: 'ARS'},
  {currency: 'AUD - Australian dollar', value: 'AUD'},
  {currency: 'AWG - Aruban florin', value: 'AWG'},
  {currency: 'AZN - Azerbaijani manat', value: 'AZN'},
  {currency: 'BAM - Bosnia and Herzegovina convertible mark', value: 'BAM'},
  {currency: 'BBD - Barbadian dollar', value: 'BBD'},
  {currency: 'BDT - Bangladeshi taka', value: 'BDT'},
  {currency: 'BGN - Bulgarian lev', value: 'BGN'},
  {currency: 'BHD - Bahraini dinar', value: 'BHD'},
  {currency: 'BIF - Burundian franc', value: 'BIF'},
  {currency: 'BMD - Bermudian dollar', value: 'BMD'},
  {currency: 'BND - Brunei dollar', value: 'BND'},
  {currency: 'BOB - Bolivian boliviano', value: 'BOB'},
  {currency: 'BRL - Brazilian real', value: 'BRL'},
  {currency: 'BSD - Bahamian dollar', value: 'BSD'},
  {currency: 'BTN - Bhutanese ngultrum', value: 'BTN'},
  {currency: 'BWP - Botswana pula', value: 'BWP'},
  {currency: 'BYN - Belarusian ruble', value: 'BYN'},
  {currency: 'BZD - Belize dollar', value: 'BZD'},
  {currency: 'CAD - Canadian dollar', value: 'CAD'},
  {currency: 'CDF - Congolese franc', value: 'CDF'},
  {currency: 'CHF - Swiss franc', value: 'CHF'},
  {currency: 'CKD[G] - Cook Islands dollar', value: 'CKD[G]'},
  {currency: 'CLP - Chilean peso', value: 'CLP'},
  {currency: 'CNY - Chinese yuan', value: 'CNY'},
  {currency: 'COP - Colombian peso', value: 'COP'},
  {currency: 'CRC - Costa Rican colónv', value: 'CRC'},
  {currency: 'CUC - Cuban convertible peso', value: 'CUC'},
  {currency: 'CUP - Cuban peso', value: 'CUP'},
  {currency: 'CVE - Cape Verdean escudo', value: 'CVE'},
  {currency: 'CZK - Czech koruna', value: 'CZK'},
  {currency: 'DJF - Djiboutian franc', value: 'DJF'},
  {currency: 'DKK - Danish krone', value: 'DKK'},
  {currency: 'DOP - Dominican peso', value: 'DOP'},
  {currency: 'DZD - Algerian dinar', value: 'DZD'},
  {currency: 'EGP - Egyptian pound', value: 'EGP'},
  {currency: 'ERN - Eritrean nakfa', value: 'ERN'},
  {currency: 'ETB - Ethiopian birr', value: 'ETB'},
  {currency: 'EUR - Euro', value: 'EUR'},
  {currency: 'FJD - Fijian dollar', value: 'FJD'},
  {currency: 'FKP - Falkland Islands pound', value: 'FKP'},
  {currency: 'FOK[G] - Faroese króna', value: 'FOK[G]'},
  {currency: 'GBP - British pound[F]', value: 'GBP'},
  {currency: 'GEL - Georgian lari', value: 'GEL'},
  {currency: 'GGP[G] - Guernsey pound', value: 'GGP[G]'},
  {currency: 'GHS - Ghanaian cedi', value: 'GHS'},
  {currency: 'GIP - Gibraltar pound', value: 'GIP'},
  {currency: 'GMD - Gambian dalasi', value: 'GMD'},
  {currency: 'GNF - Guinean franc', value: 'GNF'},
  {currency: 'GTQ - Guatemalan quetzal', value: 'GTQ'},
  {currency: 'GYD - Guyanese dollar', value: 'GYD'},
  {currency: 'HKD - Hong Kong dollar', value: 'HKD'},
  {currency: 'HNL - Honduran lempira', value: 'HNL'},
  {currency: 'HRK - Croatian kuna', value: 'HRK'},
  {currency: 'HTG - Haitian gourde', value: 'HTG'},
  {currency: 'HUF - Hungarian forint', value: 'HUF'},
  {currency: 'IDR - Indonesian rupiah', value: 'IDR'},
  {currency: 'ILS - Israeli new shekel', value: 'ILS'},
  {currency: 'IMP[G] - Manx pound', value: 'IMP[G]'},
  {currency: 'INR - Indian rupee', value: 'INR'},
  {currency: 'IQD - Iraqi dinar', value: 'IQD'},
  {currency: 'IRR - Iranian rial', value: 'IRR'},
  {currency: 'ISK - Icelandic króna', value: 'ISK'},
  {currency: 'JEP[G] - Jersey pound', value: 'JEP[G]'},
  {currency: 'JMD - Jamaican dollar', value: 'JMD'},
  {currency: 'JOD - Jordanian dinar', value: 'JOD'},
  {currency: 'JPY - Japanese yen', value: 'JPY'},
  {currency: 'KES - Kenyan shilling', value: 'KES'},
  {currency: 'KGS - Kyrgyzstani som', value: 'KGS'},
  {currency: 'KHR - Cambodian riel', value: 'KHR'},
  {currency: 'KID[G] - Kiribati dollar[E]', value: 'KID[G]'},
  {currency: 'KMF - Comorian franc', value: 'KMF'},
  {currency: 'KPW - North Korean won', value: 'KPW'},
  {currency: 'KRW - South Korean won', value: 'KRW'},
  {currency: 'KWD - Kuwaiti dinar', value: 'KWD'},
  {currency: 'KYD - Cayman Islands dollar', value: 'KYD'},
  {currency: 'KZT - Kazakhstani tenge', value: 'KZT'},
  {currency: 'LAK - Lao kip', value: 'LAK'},
  {currency: 'LBP - Lebanese pound', value: 'LBP'},
  {currency: 'LKR - Sri Lankan rupee', value: 'LKR'},
  {currency: 'LRD - Liberian dollar', value: 'LRD'},
  {currency: 'LSL - Lesotho loti', value: 'LSL'},
  {currency: 'LYD - Libyan dinar', value: 'LYD'},
  {currency: 'MAD - Moroccan dirham', value: 'MAD'},
  {currency: 'MDL - Moldovan leu', value: 'MDL'},
  {currency: 'MGA - Malagasy ariary', value: 'MGA'},
  {currency: 'MKD - Macedonian denar', value: 'MKD'},
  {currency: 'MMK - Burmese kyat', value: 'MMK'},
  {currency: 'MNT - Mongolian tögrög', value: 'MNT'},
  {currency: 'MOP - Macanese pataca', value: 'MOP'},
  {currency: 'MRU - Mauritanian ouguiya', value: 'MRU'},
  {currency: 'MUR - Mauritian rupee', value: 'MUR'},
  {currency: 'MVR - Maldivian rufiyaa', value: 'MVR'},
  {currency: 'MWK - Malawian kwacha', value: 'MWK'},
  {currency: 'MXN - Mexican peso', value: 'MXN'},
  {currency: 'MYR - Malaysian ringgit', value: 'MYR'},
  {currency: 'MZN - Mozambican metical', value: 'MZN'},
  {currency: 'NAD - Namibian dollar', value: 'NAD'},
  {currency: 'NGN - Nigerian naira', value: 'NGN'},
  {currency: 'NIO - Nicaraguan córdoba', value: 'NIO'},
  {currency: 'NOK - Norwegian krone', value: 'NOK'},
  {currency: 'NPR - Nepalese rupee', value: 'NPR'},
  {currency: 'NZD - New Zealand dollar', value: 'NZD'},
  {currency: 'OMR - Omani rial', value: 'OMR'},
  {currency: 'PAB - Panamanian balboa', value: 'PAB'},
  {currency: 'PEN - Peruvian sol', value: 'PEN'},
  {currency: 'PGK - Papua New Guinean kina', value: 'PGK'},
  {currency: 'PHP - Philippine peso', value: 'PHP'},
  {currency: 'PKR - Pakistani rupee', value: 'PKR'},
  {currency: 'PLN - Polish złoty', value: 'PLN'},
  {currency: 'PND[G] - Pitcairn Islands dollar[E]', value: 'PND[G]'},
  {currency: 'PRB[G] - Transnistrian ruble', value: 'PRB[G]'},
  {currency: 'PYG - Paraguayan guaraní', value: 'PYG'},
  {currency: 'QAR - Qatari riyal', value: 'QAR'},
  {currency: 'RON - Romanian leu', value: 'RON'},
  {currency: 'RSD - Serbian dinar', value: 'RSD'},
  {currency: 'RUB - Russian ruble', value: 'RUB'},
  {currency: 'RWF - Rwandan franc', value: 'RWF'},
  {currency: 'SAR - Saudi riyal', value: 'SAR'},
  {currency: 'SBD - Solomon Islands dollar', value: 'SBD'},
  {currency: 'SCR - Seychellois rupee', value: 'SCR'},
  {currency: 'SDG - Sudanese pound', value: 'SDG'},
  {currency: 'SEK - Swedish krona', value: 'SEK'},
  {currency: 'SGD - Singapore dollar', value: 'SGD'},
  {currency: 'SHP - Saint Helena pound', value: 'SHP'},
  {currency: 'SLL - Sierra Leonean leone', value: 'SLL'},
  {currency: 'SLS[G] - Somaliland shilling', value: 'SLS[G]'},
  {currency: 'SOS - Somali shilling', value: 'SOS'},
  {currency: 'SRD - Surinamese dollar', value: 'SRD'},
  {currency: 'SSP - South Sudanese pound', value: 'SSP'},
  {currency: 'STN - São Tomé and Príncipe dobra', value: 'STN'},
  {currency: 'SYP - Syrian pound', value: 'SYP'},
  {currency: 'SZL - Swazi lilangeni', value: 'SZL'},
  {currency: 'THB - Thai baht', value: 'THB'},
  {currency: 'TJS - Tajikistani somoni', value: 'TJS'},
  {currency: 'TMT - Turkmenistan manat', value: 'TMT'},
  {currency: 'TND - Tunisian dinar', value: 'TND'},
  {currency: 'TOP - Tongan paʻanga[P]', value: 'TOP'},
  {currency: 'TRY - Turkish lira', value: 'TRY'},
  {currency: 'TTD - Trinidad and Tobago dollar', value: 'TTD'},
  {currency: 'TVD[G] - Tuvaluan dollar', value: 'TVD[G]'},
  {currency: 'TWD - New Taiwan dollar', value: 'TWD'},
  {currency: 'TZS - Tanzanian shilling', value: 'TZS'},
  {currency: 'UAH - Ukrainian hryvnia', value: 'UAH'},
  {currency: 'UGX - Ugandan shilling', value: 'UGX'},
  {currency: 'USD - United States dollar', value: 'USD'},
  {currency: 'UYU - Uruguayan peso', value: 'UYU'},
  {currency: 'UZS - Uzbekistani soʻm', value: 'UZS'},
  {currency: 'VED - Venezuelan bolívar digital', value: 'VED'},
  {currency: 'VES - Venezuelan bolívar soberano', value: 'VES'},
  {currency: 'VND - Vietnamese đồng', value: 'VND'},
  {currency: 'VUV - Vanuatu vatu', value: 'VUV'},
  {currency: 'WST - Samoan tālā', value: 'WST'},
  {currency: 'XAF - Central African CFA franc', value: 'XAF'},
  {currency: 'XCD - Eastern Caribbean dollar', value: 'XCD'},
  {currency: 'XOF - West African CFA franc', value: 'XOF'},
  {currency: 'XPF - CFP franc', value: 'XPF'},
  {currency: 'YER - Yemeni rial', value: 'YER'},
  {currency: 'ZAR - South African rand', value: 'ZAR'},
  {currency: 'ZMW - Zambian kwacha', value: 'ZMW'},
  {currency: 'ZWB[G] - RTGS dollar[6]', value: 'ZWB[G]'},
];
