//
//

// USER ACTIONS
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';

// ACCOUNT ACTION
export const ADD_NEW_ACCOUNT_SUCCESS = 'ADD_NEW_ACCOUNT_SUCCESS';
export const GET_ACCOUNTS_DATA_SUCCESS = 'GET_ACCOUNTS_DATA_SUCCESS';
export const UPDATE_ACCOUNT_INFO_SUCCESS = 'UPDATE_ACCOUNT_INFO_SUCCESS';
export const GET_ACCOUNT_INFO_SUCCESS = 'GET_ACCOUNT_INFO_SUCCESS';
export const TOGGLE_ACCOUNT_STATUS_SUCCESS = 'TOGGLE_ACCOUNT_STATUS_SUCCESS';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
